version: '3'
services:
  realworld-db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: savingrun
      MYSQL_DATABASE: realworld
    volumes:
      - "./data:/var/lib/mysql"